steps:
  # Delete old Cloud Run service (ignore error if not found)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
    entrypoint: bash
    args:
      - -c
      - |
        gcloud run services delete detect-valid-file-from-gcs-function \
          --region=us-central1 --quiet || true

  # Deploy Cloud Function with same name
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
    entrypoint: gcloud
    args:
      - functions
      - deploy
      - detect-valid-file-from-gcs-function
      - --gen2
      - --runtime=python310
      - --trigger-event=google.storage.object.finalize
      - --trigger-resource=cloud-function-demo-dump-bucket
      - --region=us-central1
      - --entry-point=check_file_size_and_move
      - --source=.
      - --allow-unauthenticated

options:
  logging: CLOUD_LOGGING_ONLY